// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bot-demo/BotDemo.tsx": () => import("../components/mockups/bot-demo/BotDemo.tsx")
};
